### ISSUE TITLE
Error on selecting pattern as field formatter

### ISSUE THREAD

**Issue by dlopez-akalam** [pdureau/ui_patterns_field_formatters#1]
Step to reproduce it:

Install the module. Go to a entity view mode and select "pattern" as field formatter. The throber will stay turning and the log will register the following error.
```
Drupal\Component\Plugin\Exception\PluginNotFoundException: The "" plugin does not exist. Valid plugin IDs for Drupal\ui_patterns\UiPatternsManager are:  ...... in Drupal\Core\Plugin\DefaultPluginManager->doGetDefinition() (line 53 of /var/www/html/web/core/lib/Drupal/Component/Plugin/Discovery/DiscoveryTrait.php).
```

The reason is the default empty pattern is used to generate the formatter summary.

**Comment by dlopez-akalam** [comment]
#2

**Comment by pdureau** [comment]
Thanks @dlopez-akalam  I will have a look on your PR

**Comment by pdureau** [comment]
Merged
