### ISSUE TITLE
Insufficient checks of pattern variants presence/absence

### ISSUE THREAD

**Issue by idiazroncero** [pdureau/ui_patterns_field_formatters#3]
I have put together several related issues with pattern variant checks.:

------

On settingsForm(), it is assumed that the pattern will have at least one variant declared and present:
```
    $configuration['pattern_variant'] = $this->getSetting('variants')[$pattern];
```

**Steps to reproduce:**
- Apply a "pattern" field formatter to a variant-less pattern.
- settingsForm() will fail and produce an error when trying to configure the field.

------

If this error is corrected, on other parts a check is made but in some cases it will wrongly pass and give false posives (i.e, on settingsSummary, when changing the field from a pattern with variants to a pattern without, you'll get the $variants array populated with the data from the first one)

```    
if (!empty($this->getSetting('variants'))) {
      $variant = $this->getSetting('variants')[$pattern->id()];
      $variant = $pattern->getVariant($variant)->getLabel();
      $summary[] = $this->t('Variant: @variant', ['@variant' => $variant]);
}
```

**Steps to reproduce:**
- Apply a pattern with variants to a field
- Change the pattern to a variant-less version
- settingsSummary() will fail because on the transition, the variant of the first pattern will be passed and `empty($this->getSetting('variants')` will wrongly pass leading to errors.

------

If this error is corrected, a new problem also happens on viewElements(), so it seems somehow the $variant data is not correctly unset when passing from a variant-enabled pattern to a variant-less one and the latest inherits the $variant from the first one.

```
      if (!empty($this->getSetting('variants'))) {
        $variant = $this->getSetting('variants')[$pattern];
        $elements[$delta]['#variant'] = $variant;
      }
```

**Steps to reproduce:**
- Apply a pattern with variants to a field
- Change the pattern to a variant-less version
- On field view, the variant-less pattern will still receive the $variant data from the first pattern. This won't cause any visible errors most of the time, but is still wrong.

I'm working on a patch and will make a PR once finished.

**Comment by pdureau** [comment]
Thanks @idiazroncero I am glad you use & like this module. I am waiting for your PR.

**Comment by idiazroncero** [comment]
Yes @pdureau we're finding it very useful. We wanted to drop the display suite dependency for rendering fields as patterns on a project and we came across your work, which fits perfectly... Thank you for your work!

**Comment by idiazroncero** [comment]
Patch ready to review on https://github.com/pdureau/ui_patterns_field_formatters/pull/5
Be kind, i'm a front-end dev ;)

**Comment by pdureau** [comment]
@idiazroncero Don't worry, I am not a dev at all :) Not at the professional level.

**Comment by pdureau** [comment]
Merged. Can you tell me if this is OK on your side?

**Comment by idiazroncero** [comment]
Everything’s fine. Tested and it works, thanks!
